### ISSUE TITLE
illumina paire-end reads

### ISSUE THREAD

**Issue by SC-Duan** [CMU-SAFARI/Apollo#2]
Hi,
I just have illumina pair-end reads, can I cat the R1.fa and R2.fa together as reads.fa to do polish?
Thank you!

**Comment by canfirtina** [comment]
Hello,

Yes, it is possible to use the paired-end reads as you suggested. Please also make sure that the ids of the two pairs are not identical in reads.fa file (e.g., having both >pair_1/1 and pair_1/2 in reads.fa is OK but pair_1 /1 and pair_1 /2 is not OK because the ids of the both reads are pair_1).

**Comment by SC-Duan** [comment]
Thank you!
