### ISSUE TITLE
Segmentation fault      (core dumped)

### ISSUE THREAD

**Issue by sanvva** [CMU-SAFARI/Apollo#3]
$ gdb core-file core.87716
[New LWP 87733]
Core was generated by `apollo -a R1_nanopore_canu_contig00000027.fasta -r miseq_R1_filtered.fasta -r b'.
Program terminated with signal 11, Segmentation fault.
#0  0x00002acc19096c52 in ?? ()

**Comment by canfirtina** [comment]
Hello,

Can you please provide the full command that you used to run Apollo? Do you specify the alignment files in the same order that you specify the reads files (e.g., -r r1.fasta -r r2.fasta -m r1.bam -m r2.bam)?

**Comment by sanvva** [comment]
> Hello,
> 
> Can you please provide the full command that you used to run Apollo? Do you specify the alignment files in the same order that you specify the reads files (e.g., -r r1.fasta -r r2.fasta -m r1.bam -m r2.bam)?

apollo -a R1_nanopore_canu_contig00000027.fasta -r miseq_R1_filtered.fasta -r blasr_20190222-NPL0714-P2-E11-H11.pass.fasta -m R1.miseq.nano-canu.aln-pe.sort.bam -m R1_nanopore_canu_contig00000027_blasr_20190222.bam -t 120 -o R1_nano_canu_apollo_polished.fasta

**Comment by sanvva** [comment]
yes, they are in the same order. 
My server is Centos 7 whith gcc4.8.5. 
When installing Apollo ,error occured "g++: error: unrecognized command line option ‘-std=c++14’".
So I installed gcc6.
 $ sudo yum install centos-release-scl -y
$ sudo yum install devtoolset-6-gcc devtoolset-6-gcc-c++
$ scl enable devtoolset-6 bash

**Comment by canfirtina** [comment]
The command you used seem correct. Unfortunately, it is not possible for me to reconstruct the error you get without the data you use. I can suggest two options to understand the reason of this error.

1. If you change the line 13 in Makefile:

https://github.com/CMU-SAFARI/Apollo/blob/0b96086e87a86ea7d4a92112edddadb41a9134f7/Makefile#L13 

to

`CXXLAGS=$(INC_PARAMS) -std=c++14 -g -O0 -DSEQAN_ENABLE_DEBUG=1 -DSEQAN_HAS_ZLIB=1 -DSEQAN_HAS_BZIP2=1 -DSEQAN_DISABLE_VERSION_CHECK=YES -W -Wall -pedantic`

And if you compile the source code again after cleaning the previous compilation (i.e., `make clean`), this will enable debugging option and you can use gdb again to get more information about the error. Please also inform if you choose to follow approach.

2. Is it possible for you to share the data with us? If so, how large is the data? I can provide you with a link where you can upload files up to 300GB. If you think this is feasible, we can test it in our servers and inform you once we identify the problem.

**Comment by sanvva** [comment]
@canfirtina I re-make Apollo following your first option, but got the same error. 

This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
core-file: No such file or directory.
[New LWP 375186]
[New LWP 375193]
[New LWP 375194]
[New LWP 375396]
[New LWP 375397]
[New LWP 375399]
[New LWP 375400]
[New LWP 375206]
[New LWP 375405]
[New LWP 375407]
[New LWP 375406]
[New LWP 375196]
[New LWP 375192]
[New LWP 375191]
[New LWP 375197]
[New LWP 375201]
[New LWP 375195]
[New LWP 375198]
[New LWP 375199]
[New LWP 375202]
[New LWP 375200]
[New LWP 375402]
[New LWP 375204]
[New LWP 375205]
[New LWP 375203]
[New LWP 375401]
[New LWP 375393]
[New LWP 375398]
[New LWP 375395]
[New LWP 375403]
[New LWP 375408]
[New LWP 375394]
[New LWP 375404]
Core was generated by `apollo -a R1_nanopore_canu_contig00000027.fasta -r miseq_R1_filtered.fasta -r b'.
Program terminated with signal 11, Segmentation fault.
#0  0x00002b2c41dba9f6 in ?? ()



My dataset is small, about 2GB. May you please give me a line to upload them? It's a plant chloroplast genome, assembled by Nanopore dataset. I want to polish it using both nanopore dataset and Miseq dataset.

**Comment by canfirtina** [comment]
Please upload your files (i.e., assembly, fasta, and bam files) using the link below (the quota is around 50GB):

https://polybox.ethz.ch/index.php/s/nsm3pUXJDAGb8gd

Thanks.

**Comment by sanvva** [comment]
@canfirtina All files uploaded! Looking forward!

**Comment by canfirtina** [comment]
@sanvva Got it! We'll take a look at it as soon as possible. Thanks for sharing the data

**Comment by sanvva** [comment]
@canfirtina Have some good news?

**Comment by canfirtina** [comment]
Hi @sanvva . Yes, I think I was able to detect the cause of the problem. In "miseq_R1_filtered.fasta" there are probably paired-end reads because the file has a read with id:

`>M03069:134:000000000-BY88M:1:1109:3885:15639 1:N:0:6`

and also with id

`>M03069:134:000000000-BY88M:1:1109:3885:15639 2:N:0:6`

Note that the read name of these two reads are actually _identical_ because both of their read name is "M03069:134:000000000-BY88M:1:1109:3885:15639" (as also reported in R1.miseq.nano-canu.aln-pe.sort.bam file).

This causes a problem because Apollo does not support having reads with the same read name, which is usually the case when you have paired-end reads. To exemplify what I just said, take this example:

canu.aln-pe.sort.bam file has an alignment record like this:

`M03069:134:000000000-BY88M:1:1109:3885:15639    161     R1_nanopore_canu_contig00000027 13807   0       183M68S =       181692  168133  AGATTCATTTCATTATGGATGAATAAGTCTTGATGCTTTATAACATTGCCTTTTATGATGAGGCGAATTCAAAATTGTTCGAATTGTGTAATCGTCAATTACTGACAGTGGTAAACGACCCAAAGCAATTTGATTATAATTCAATTCGTGACGATCATAAGTAGAAAGTTCATATTCTTCAGTTCATTACAATATTCTGCTGAATCCATTTCTTTTTCTAGGCCTGCCACTTTATCTTTTCTTTTTTAATG     6CBCCGFGFGGGGGGGFGFEFGGGCGGGGGGGGGGCCGFG9,CFFG<CFGGGGCFGFFGGGGGFGGGGFGGGGGGFFFGGGGGGGFGFGGGGGGGGGGGGGGFGGGGGFGGGGFGGGEG=CFGGGGFGFGEFGGFGGCGGGGGGGGGFGGEECGGGGGDFFFGC9E?EBFFGDFGGGFGGFFFGGGGGGFGCGGG,DEFAC8,=DFGCFGGDFCGGCFGF9DC3DE@<<?5=3?DCGCEGGFFGFFGFGG,     NM:i:1  MD:Z:41T141     MC:Z:4M1I91M1I153M      AS:i:178        XS:i:178        SA:Z:R1_nanopore_canu_contig00000027,224957,-,4M1I29M1I34M182S,0,2;     XA:Z:R1_nanopore_canu_contig00000027,+30003,183M68S,1;R1_nanopore_canu_contig00000027,-179982,68S183M,1;R1_nanopore_canu_contig00000027,+213045,183M68S,1;R1_nanopore_canu_contig00000027,+229176,183M68S,1;R1_nanopore_canu_contig00000027,-196170,68S183M,1;`

Notice that the flag says that the second pair is mapped because the flag bit "128" is set. However, since Apollo does check this paired-end flag bits, it fetches the first pair because it is the one that appears first in the file  when we search the read name "M03069:134:000000000-BY88M:1:1109:3885:15639". While preprocessing it, it tries to erase the last 68 bases (68S in CIGAR) after skipping 183 bases (183M in CIGAR). However, the length of the first pair is 250 while the length of the second pair is 251 (183 + 68). Therefore, the exception is caused because Apollo tries to remove the character 251 that is not allocated for the first pair.

For now, I would suggest you to make sure that the read names are unique excluding what comes after the first white space in the read name. For example, if you have pairs, you can just remove all of the white spaces from the read id and map these reads to your assembly.

In the meantime, I will push a new commit so that Apollo catches such exceptions and throws a proper output to report the problems.

Please also check the suggestions that we list in the README.md file:

https://github.com/CMU-SAFARI/Apollo#input-format

**Comment by sanvva** [comment]
@canfirtina Thank you very much! Yes, "miseq_R1_filtered.fasta" is a concatenate file created by 'cat' the forward and reverse Illumina paired-end files. Sorry for ignoring your README.md file. Thanks again!

**Comment by canfirtina** [comment]
Glad to help. As an another suggestion, I would also suggest you to use the [chunk_reads.sh](https://github.com/CMU-SAFARI/Apollo/blob/master/utils/chunk_reads.sh) file to divide your reads in "blasr_20190222-NPL0714-P2-E11-H11.pass.fasta" into smaller sequences (e.g., chunks of 1000bps or 5000bps) as it may be possible for Apollo to use more memory with ultra long reads (e.g., longer than 50kbps).

I also pushed a new commit that ignores the mapping when the flag bit is set to 128: https://github.com/CMU-SAFARI/Apollo/commit/b39cf8efe8a337e4af76289705b08fed9c6a86b3

You can use the latest code with the data set you sent but it will ignore all of the mappings when the second pair is mapped.

**Comment by sanvva** [comment]
@canfirtina I'll try it too. Thx!
